### ISSUE TITLE
Bug: 2717: unknown share table hits of share tnc7yee14.ontime_shared_2 on DROP TABLE

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#11079]
**Summary**

this issue can be considered as a follow up of https://github.com/datafuselabs/databend/issues/11046

I guess sharing is not a functionality on the main paths, we'd better to avoid it breaks the normal operations on anything goes wrong about sharing.

**Comment by lichuang** [comment]
this bug has been fixed, please use [v1.0.63-nightly](https://github.com/datafuselabs/databend/releases/tag/v1.0.63-nightly) instead.

**Comment by flaneur2020** [comment]
@lichuang I've upgraded to v1.1.3 and this issue still remains, this error might be raised from another code path.
